### ISSUE TITLE
Provide indication of initial loading

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/cups-messenger-ui#33]
Currently, users may not realize that Tor is still bootstrapping and the initial syncing is taking place. This may cause a user to open the app, see nothing has changed, and close the app. Meanwhile, had they waited 10-15 seconds, they would have seen new messages/contacts appear. We should have a non-blocking loading indicator or toast to convey what's happening.

**Comment by afg419** [comment]
WIP, works from minimized state, but not from opening app fresh (while authed)

**Comment by afg419** [comment]
040
